version: "3.8"

services:
  url-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: url_sql_server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ZipURL@Password123
    volumes:
      - url_db_data:/var/opt/mssql

volumes:
  url_db_data:
